### ISSUE TITLE
SplashScreen: java.lang.NullPointerException

### ISSUE THREAD

**Issue by paamrutk** [apache/cordova-plugin-splashscreen#196] opened 2019-05-02 07:42 UTC
Hello all,

We have found this error on Google Play Store console that seams to be an SplashScreen problem

java.lang.NullPointerException: 
  at org.apache.cordova.splashscreen.SplashScreen$4.run (SplashScreen.java:230)
  at android.app.Activity.runOnUiThread (Activity.java:6404)
  at org.apache.cordova.splashscreen.SplashScreen.removeSplashScreen (SplashScreen.java:220)
  at org.apache.cordova.splashscreen.SplashScreen.onMessage (SplashScreen.java:190)
  at org.apache.cordova.PluginManager.postMessage (PluginManager.java:312)
  at org.apache.cordova.CordovaWebViewImpl.postMessage (CordovaWebViewImpl.java:379)
  at org.apache.cordova.splashscreen.SplashScreen$2.run (SplashScreen.java:166)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7045)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:964)

Please help on this I am getting this crash issue frequently.

**Comment by janpio** [comment] 2019-05-02 08:37
What version of the plugin?
What version of Cordova Android?

Current codebase looks like this:
https://github.com/apache/cordova-plugin-splashscreen/blob/8490496c0b5ecdb8798a3c3a4b93f0a3fe85c928/src/android/SplashScreen.java#L222-L230
There is an explicit Null-check before line 230 that should avoid this problem.

**Comment by paamrutk** [comment] 2019-05-02 12:34
Plugin Version:5.0.2
Cordova Android Version:7.1.4

**Comment by timbru31** [comment] 2019-05-05 15:09
This seems like a duplicate of #178 - I'm closing this one

**Closed by timbru31** 2019-05-05 15:09 UTC
